name: push
on: 
  push: 
    branches:
        - '*'
env:
  RUNNER_OS: ${{runner.os}}
jobs:
  build:
    uses: poornaakallam/workflows/.github/workflows/poc.yml@main
    with: 
      path: ~/.m2/repository
      key: "${env.RUNNER_OS}-maven-('**/pom.xml')"
        
      #cmd: mvn -f pom.xml clean package
      #upload-path: ./poorna.zip
    secrets:
      access-key: ${{ secrets.access_key }}
      secret-key: ${{secrets.secret_key}}

      

      
