name: push
on: 
  push: 
    branches:
        - '*'
jobs:
  build:
    uses: poornaakallam/workflows/.github/workflows/poc.yml@main
    with: 
      path: ./
      key: pom.xml
      upload-path: ./poorna.zip
    secrets:
      access-key: ${{ secrets.access_key }}
      secret-key: ${{secrets.secret_key}}

      

      
